const employees = [
  {
    firstName: 'LeBron',
    lastName: 'James',
    street: '123 Main Street',
    city: 'Los Angeles',
    dateOfBirth: '12/30/1984',
    startDate: '07/01/2003',
    zipCode: '90001',
    department: 'Sales',
    state: 'AL, Alabama',
  },
  {
    firstName: 'Kobe',
    lastName: 'Bryant',
    street: '456 Elm Street',
    city: 'Los Angeles',
    dateOfBirth: '08/23/1978',
    startDate: '11/01/1996',
    zipCode: '90002',
    department: 'Marketing',
    state: 'CA, California',
  },
  {
    firstName: 'Michael',
    lastName: 'Jordan',
    street: '789 Oak Avenue',
    city: 'Chicago',
    dateOfBirth: '02/17/1963',
    startDate: '10/26/1984',
    zipCode: '60601',
    department: 'Engineering',
    state: 'IL, Illinois',
  },
  {
    firstName: 'Magic',
    lastName: 'Johnson',
    street: '1011 Pine Street',
    city: 'Los Angeles',
    dateOfBirth: '08/14/1959',
    startDate: '10/01/1979',
    zipCode: '90004',
    department: 'Legal',
    state: 'CA, California',
  },
  {
    firstName: 'Larry',
    lastName: 'Bird',
    street: '1313 Maple Avenue',
    city: 'Boston',
    dateOfBirth: '12/07/1956',
    startDate: '06/01/1979',
    zipCode: '02108',
    department: 'Human Resources',
    state: 'MA, Massachusetts',
  },
  {
    firstName: 'John',
    lastName: 'Doe',
    street: '789 Elm Street',
    city: 'New York',
    dateOfBirth: '05/15/1980',
    startDate: '09/01/2002',
    zipCode: '10001',
    department: 'Sales',
    state: 'NY, New York',
  },
  {
    firstName: 'Jane',
    lastName: 'Smith',
    street: '456 Oak Avenue',
    city: 'San Francisco',
    dateOfBirth: '03/25/1990',
    startDate: '12/01/2012',
    zipCode: '94101',
    department: 'Engineering',
    state: 'CA, California',
  },
  {
    firstName: 'David',
    lastName: 'Johnson',
    street: '789 Pine Street',
    city: 'Seattle',
    dateOfBirth: '07/10/1975',
    startDate: '08/01/1998',
    zipCode: '98101',
    department: 'Marketing',
    state: 'WA, Washington',
  },
  {
    firstName: 'Sarah',
    lastName: 'Williams',
    street: '1011 Cedar Avenue',
    city: 'Chicago',
    dateOfBirth: '11/18/1988',
    startDate: '05/01/2010',
    zipCode: '60602',
    department: 'Human Resources',
    state: 'IL, Illinois',
  },
  {
    firstName: 'Robert',
    lastName: 'Brown',
    street: '1313 Walnut Street',
    city: 'Dallas',
    dateOfBirth: '09/02/1973',
    startDate: '04/01/1996',
    zipCode: '75201',
    department: 'Engineering',
    state: 'TX, Texas',
  },
  {
    firstName: 'Jennifer',
    lastName: 'Davis',
    street: '789 Maple Avenue',
    city: 'Miami',
    dateOfBirth: '01/12/1985',
    startDate: '03/01/2007',
    zipCode: '33101',
    department: 'Sales',
    state: 'FL, Florida',
  },
  {
    firstName: 'William',
    lastName: 'Miller',
    street: '456 Oak Street',
    city: 'Boston',
    dateOfBirth: '06/05/1979',
    startDate: '02/01/2001',
    zipCode: '02101',
    department: 'Legal',
    state: 'MA, Massachusetts',
  },
  {
    firstName: 'Emily',
    lastName: 'Anderson',
    street: '1011 Pine Avenue',
    city: 'Los Angeles',
    dateOfBirth: '04/28/1992',
    startDate: '01/01/2014',
    zipCode: '90005',
    department: 'Marketing',
    state: 'CA, California',
  },
  {
    firstName: 'Daniel',
    lastName: 'Clark',
    street: '1313 Elm Street',
    city: 'New York',
    dateOfBirth: '10/09/1983',
    startDate: '12/01/2005',
    zipCode: '10002',
    department: 'Human Resources',
    state: 'NY, New York',
  },
  {
    firstName: 'Olivia',
    lastName: 'Young',
    street: '789 Oak Avenue',
    city: 'Seattle',
    dateOfBirth: '07/20/1995',
    startDate: '11/01/2017',
    zipCode: '98102',
    department: 'Sales',
    state: 'WA, Washington',
  },
  {
    firstName: 'Matthew',
    lastName: 'Lee',
    street: '456 Cedar Street',
    city: 'Chicago',
    dateOfBirth: '02/13/1976',
    startDate: '10/01/1999',
    zipCode: '60603',
    department: 'Engineering',
    state: 'IL, Illinois',
  },
  {
    firstName: 'Ava',
    lastName: 'Garcia',
    street: '1011 Walnut Avenue',
    city: 'Dallas',
    dateOfBirth: '12/01/1987',
    startDate: '09/01/2009',
    zipCode: '75202',
    department: 'Marketing',
    state: 'TX, Texas',
  },
  {
    firstName: 'James',
    lastName: 'Lopez',
    street: '1313 Maple Street',
    city: 'Miami',
    dateOfBirth: '08/05/1980',
    startDate: '07/01/2002',
    zipCode: '33102',
    department: 'Legal',
    state: 'FL, Florida',
  },
  {
    firstName: 'Sophia',
    lastName: 'Martinez',
    street: '789 Pine Avenue',
    city: 'Boston',
    dateOfBirth: '03/17/1993',
    startDate: '06/01/2015',
    zipCode: '02102',
    department: 'Human Resources',
    state: 'MA, Massachusetts',
  },
  {
    firstName: 'Benjamin',
    lastName: 'Hall',
    street: '456 Cedar Avenue',
    city: 'Los Angeles',
    dateOfBirth: '09/28/1982',
    startDate: '05/01/2004',
    zipCode: '90006',
    department: 'Sales',
    state: 'CA, California',
  },
  {
    firstName: 'Isabella',
    lastName: 'Young',
    street: '1011 Elm Street',
    city: 'New York',
    dateOfBirth: '05/08/1994',
    startDate: '04/01/2016',
    zipCode: '10003',
    department: 'Engineering',
    state: 'NY, New York',
  },
  {
    firstName: 'Joseph',
    lastName: 'King',
    street: '1313 Oak Avenue',
    city: 'Seattle',
    dateOfBirth: '01/22/1986',
    startDate: '03/01/2008',
    zipCode: '98103',
    department: 'Marketing',
    state: 'WA, Washington',
  },
  {
    firstName: 'Mia',
    lastName: 'Scott',
    street: '789 Maple Street',
    city: 'Chicago',
    dateOfBirth: '06/14/1977',
    startDate: '02/01/2000',
    zipCode: '60604',
    department: 'Legal',
    state: 'IL, Illinois',
  },
  {
    firstName: 'Ethan',
    lastName: 'Gonzalez',
    street: '1011 Walnut Avenue',
    city: 'Dallas',
    dateOfBirth: '10/25/1989',
    startDate: '01/01/2011',
    zipCode: '75203',
    department: 'Human Resources',
    state: 'TX, Texas',
  },
  {
    firstName: 'Charlotte',
    lastName: 'Walker',
    street: '1313 Pine Street',
    city: 'Miami',
    dateOfBirth: '04/30/1991',
    startDate: '12/01/2013',
    zipCode: '33103',
    department: 'Sales',
    state: 'FL, Florida',
  },
  {
    firstName: 'Alexander',
    lastName: 'Lewis',
    street: '456 Cedar Avenue',
    city: 'Boston',
    dateOfBirth: '09/13/1984',
    startDate: '11/01/2006',
    zipCode: '02103',
    department: 'Engineering',
    state: 'MA, Massachusetts',
  },
  {
    firstName: 'Amelia',
    lastName: 'Allen',
    street: '1011 Oak Street',
    city: 'Los Angeles',
    dateOfBirth: '03/16/1996',
    startDate: '10/01/2018',
    zipCode: '90007',
    department: 'Marketing',
    state: 'CA, California',
  },
  {
    firstName: 'Daniel',
    lastName: 'Clark',
    street: '1313 Elm Avenue',
    city: 'New York',
    dateOfBirth: '11/29/1987',
    startDate: '09/01/2009',
    zipCode: '10004',
    department: 'Human Resources',
    state: 'NY, New York',
  },
  {
    firstName: 'Sofia',
    lastName: 'White',
    street: '789 Maple Street',
    city: 'Seattle',
    dateOfBirth: '07/19/1999',
    startDate: '08/01/2021',
    zipCode: '98104',
    department: 'Sales',
    state: 'WA, Washington',
  },
  {
    firstName: 'Andrew',
    lastName: 'Harris',
    street: '456 Oak Avenue',
    city: 'Chicago',
    dateOfBirth: '02/03/1981',
    startDate: '07/01/2003',
    zipCode: '60605',
    department: 'Engineering',
    state: 'IL, Illinois',
  },
  {
    firstName: 'Scarlett',
    lastName: 'Young',
    street: '1011 Pine Street',
    city: 'Dallas',
    dateOfBirth: '12/09/1992',
    startDate: '06/01/2014',
    zipCode: '75204',
    department: 'Marketing',
    state: 'TX, Texas',
  },
  {
    firstName: 'Logan',
    lastName: 'Lee',
    street: '1313 Walnut Avenue',
    city: 'Miami',
    dateOfBirth: '08/12/1985',
    startDate: '05/01/2007',
    zipCode: '33104',
    department: 'Legal',
    state: 'FL, Florida',
  },
  {
    firstName: 'Harper',
    lastName: 'Martin',
    street: '789 Cedar Street',
    city: 'Boston',
    dateOfBirth: '01/24/1997',
    startDate: '04/01/2019',
    zipCode: '02104',
    department: 'Human Resources',
    state: 'MA, Massachusetts',
  },
  {
    firstName: 'Henry',
    lastName: 'Garcia',
    street: '456 Oak Avenue',
    city: 'Los Angeles',
    dateOfBirth: '06/07/1988',
    startDate: '03/01/2010',
    zipCode: '90008',
    department: 'Sales',
    state: 'CA, California',
  },
  {
    firstName: 'Luna',
    lastName: 'Smith',
    street: '1011 Elm Avenue',
    city: 'New York',
    dateOfBirth: '05/26/1990',
    startDate: '02/01/2012',
    zipCode: '10005',
    department: 'Engineering',
    state: 'NY, New York',
  },
  {
    firstName: 'Jackson',
    lastName: 'Johnson',
    street: '1313 Maple Street',
    city: 'Seattle',
    dateOfBirth: '01/28/1982',
    startDate: '12/01/2004',
    zipCode: '98105',
    department: 'Marketing',
    state: 'WA, Washington',
  },
  {
    firstName: 'Penelope',
    lastName: 'Davis',
    street: '789 Oak Avenue',
    city: 'Chicago',
    dateOfBirth: '06/25/1973',
    startDate: '10/01/1996',
    zipCode: '60606',
    department: 'Legal',
    state: 'IL, Illinois',
  },
  {
    firstName: 'Gabriel',
    lastName: 'Rodriguez',
    street: '1011 Pine Street',
    city: 'Dallas',
    dateOfBirth: '10/03/1984',
    startDate: '09/01/2006',
    zipCode: '75205',
    department: 'Human Resources',
    state: 'TX, Texas',
  },
  {
    firstName: 'Stella',
    lastName: 'Clark',
    street: '1313 Walnut Avenue',
    city: 'Miami',
    dateOfBirth: '04/05/1996',
    startDate: '08/01/2018',
    zipCode: '33105',
    department: 'Sales',
    state: 'FL, Florida',
  },
  {
    firstName: 'Zachary',
    lastName: 'Lewis',
    street: '456 Cedar Street',
    city: 'Boston',
    dateOfBirth: '09/08/1987',
    startDate: '07/01/2009',
    zipCode: '02105',
    department: 'Engineering',
    state: 'MA, Massachusetts',
  },
  {
    firstName: 'Violet',
    lastName: 'Taylor',
    street: '1011 Oak Avenue',
    city: 'Los Angeles',
    dateOfBirth: '03/20/1999',
    startDate: '06/01/2021',
    zipCode: '90009',
    department: 'Marketing',
    state: 'CA, California',
  },
  {
    firstName: 'Luke',
    lastName: 'Allen',
    street: '1313 Elm Avenue',
    city: 'New York',
    dateOfBirth: '11/23/1980',
    startDate: '09/01/2002',
    zipCode: '10006',
    department: 'Human Resources',
    state: 'NY, New York',
  },
  {
    firstName: 'Hazel',
    lastName: 'Brown',
    street: '789 Maple Street',
    city: 'Seattle',
    dateOfBirth: '07/15/1992',
    startDate: '11/01/2014',
    zipCode: '98106',
    department: 'Sales',
    state: 'WA, Washington',
  },
  {
    firstName: 'Ryan',
    lastName: 'Adams',
    street: '456 Oak Avenue',
    city: 'Chicago',
    dateOfBirth: '02/09/1984',
    startDate: '10/01/2006',
    zipCode: '60607',
    department: 'Engineering',
    state: 'IL, Illinois',
  },
  {
    firstName: 'Avery',
    lastName: 'Morris',
    street: '1011 Pine Street',
    city: 'Dallas',
    dateOfBirth: '12/05/1995',
    startDate: '08/01/2017',
    zipCode: '75206',
    department: 'Legal',
    state: 'TX, Texas',
  },
  {
    firstName: 'Evelyn',
    lastName: 'Hernandez',
    street: '1313 Walnut Avenue',
    city: 'Miami',
    dateOfBirth: '08/08/1978',
    startDate: '06/01/2000',
    zipCode: '33106',
    department: 'Human Resources',
    state: 'FL, Florida',
  },
  {
    firstName: 'Carter',
    lastName: 'King',
    street: '789 Cedar Street',
    city: 'Boston',
    dateOfBirth: '01/19/1990',
    startDate: '04/01/2012',
    zipCode: '02106',
    department: 'Sales',
    state: 'MA, Massachusetts',
  },
  {
    firstName: 'Mila',
    lastName: 'Garcia',
    street: '1011 Oak Avenue',
    city: 'Los Angeles',
    dateOfBirth: '03/30/2002',
    startDate: '02/01/2024',
    zipCode: '90010',
    department: 'Engineering',
    state: 'CA, California',
  },
  {
    firstName: 'Jack',
    lastName: 'Johnson',
    street: '1313 Elm Avenue',
    city: 'New York',
    dateOfBirth: '11/22/1983',
    startDate: '12/01/2005',
    zipCode: '10007',
    department: 'Human Resources',
    state: 'NY, New York',
  },
  {
    firstName: 'Layla',
    lastName: 'Jones',
    street: '789 Maple Street',
    city: 'Seattle',
    dateOfBirth: '07/14/1995',
    startDate: '10/01/2017',
    zipCode: '98107',
    department: 'Marketing',
    state: 'WA, Washington',
  },
  {
    firstName: 'Wyatt',
    lastName: 'Thompson',
    street: '456 Cedar Avenue',
    city: 'Chicago',
    dateOfBirth: '02/17/1987',
    startDate: '09/01/2009',
    zipCode: '60608',
    department: 'Sales',
    state: 'IL, Illinois',
  },
  {
    firstName: 'Victoria',
    lastName: 'Adams',
    street: '1011 Walnut Street',
    city: 'Dallas',
    dateOfBirth: '12/02/1998',
    startDate: '07/01/2021',
    zipCode: '75207',
    department: 'Legal',
    state: 'TX, Texas',
  },
  {
    firstName: 'Leo',
    lastName: 'Taylor',
    street: '1313 Pine Street',
    city: 'Miami',
    dateOfBirth: '08/27/1989',
    startDate: '05/01/2013',
    zipCode: '33107',
    department: 'Human Resources',
    state: 'FL, Florida',
  },
  {
    firstName: 'Lillian',
    lastName: 'Wilson',
    street: '789 Cedar Avenue',
    city: 'Boston',
    dateOfBirth: '01/31/1981',
    startDate: '04/01/2003',
    zipCode: '02107',
    department: 'Sales',
    state: 'MA, Massachusetts',
  },
  {
    firstName: 'Sebastian',
    lastName: 'Miller',
    street: '456 Oak Street',
    city: 'Los Angeles',
    dateOfBirth: '06/10/1992',
    startDate: '03/01/2014',
    zipCode: '90011',
    department: 'Engineering',
    state: 'CA, California',
  },
  {
    firstName: 'Zoe',
    lastName: 'Thomas',
    street: '1011 Elm Street',
    city: 'New York',
    dateOfBirth: '05/03/1994',
    startDate: '02/01/2016',
    zipCode: '10008',
    department: 'Human Resources',
    state: 'NY, New York',
  },
  {
    firstName: 'Xavier',
    lastName: 'Robinson',
    street: '1313 Maple Street',
    city: 'Seattle',
    dateOfBirth: '12/23/1985',
    startDate: '01/01/2008',
    zipCode: '98108',
    department: 'Marketing',
    state: 'WA, Washington',
  },
  {
    firstName: 'Autumn',
    lastName: 'Parker',
    street: '789 Oak Avenue',
    city: 'Chicago',
    dateOfBirth: '06/16/1976',
    startDate: '12/01/1999',
    zipCode: '60609',
    department: 'Sales',
    state: 'IL, Illinois',
  },
  {
    firstName: 'Nolan',
    lastName: 'White',
    street: '1011 Pine Avenue',
    city: 'Dallas',
    dateOfBirth: '10/08/1987',
    startDate: '11/01/2009',
    zipCode: '75208',
    department: 'Engineering',
    state: 'TX, Texas',
  },
  {
    firstName: 'Lucy',
    lastName: 'Harris',
    street: '1313 Walnut Avenue',
    city: 'Miami',
    dateOfBirth: '04/11/1999',
    startDate: '10/01/2021',
    zipCode: '33108',
    department: 'Legal',
    state: 'FL, Florida',
  },
  {
    firstName: 'Eli',
    lastName: 'Gonzalez',
    street: '789 Cedar Street',
    city: 'Boston',
    dateOfBirth: '01/05/1991',
    startDate: '09/01/2013',
    zipCode: '02108',
    department: 'Human Resources',
    state: 'MA, Massachusetts',
  },
  {
    firstName: 'Aurora',
    lastName: 'Young',
    street: '456 Oak Avenue',
    city: 'Los Angeles',
    dateOfBirth: '03/15/2003',
    startDate: '08/01/2025',
    zipCode: '90012',
    department: 'Marketing',
    state: 'CA, California',
  },
  {
    firstName: 'Grayson',
    lastName: 'Lewis',
    street: '1011 Elm Street',
    city: 'New York',
    dateOfBirth: '11/18/1984',
    startDate: '07/01/2006',
    zipCode: '10009',
    department: 'Human Resources',
    state: 'NY, New York',
  },
  {
    firstName: 'Ruby',
    lastName: 'Anderson',
    street: '1313 Maple Avenue',
    city: 'Seattle',
    dateOfBirth: '07/12/1996',
    startDate: '06/01/2018',
    zipCode: '98109',
    department: 'Sales',
    state: 'WA, Washington',
  },
  {
    firstName: 'Miles',
    lastName: 'Thomas',
    street: '789 Oak Street',
    city: 'Chicago',
    dateOfBirth: '02/07/1988',
    startDate: '05/01/2010',
    zipCode: '60610',
    department: 'Engineering',
    state: 'IL, Illinois',
  },
  {
    firstName: 'Emma',
    lastName: 'Wilson',
    street: '1011 Pine Avenue',
    city: 'Dallas',
    dateOfBirth: '09/10/1999',
    startDate: '04/01/2022',
    zipCode: '75209',
    department: 'Legal',
    state: 'TX, Texas',
  },
  {
    firstName: 'Sawyer',
    lastName: 'Robinson',
    street: '1313 Walnut Street',
    city: 'Miami',
    dateOfBirth: '08/24/1980',
    startDate: '03/01/2002',
    zipCode: '33109',
    department: 'Human Resources',
    state: 'FL, Florida',
  },
  {
    firstName: 'Penelope',
    lastName: 'Parker',
    street: '789 Cedar Avenue',
    city: 'Boston',
    dateOfBirth: '01/28/1992',
    startDate: '02/01/2014',
    zipCode: '02109',
    department: 'Sales',
    state: 'MA, Massachusetts',
  },
  {
    firstName: 'Austin',
    lastName: 'Gonzalez',
    street: '456 Oak Street',
    city: 'Los Angeles',
    dateOfBirth: '06/02/2004',
    startDate: '01/01/2026',
    zipCode: '90013',
    department: 'Engineering',
    state: 'CA, California',
  },
  {
    firstName: 'Aria',
    lastName: 'Young',
    street: '1011 Elm Street',
    city: 'New York',
    dateOfBirth: '11/15/1985',
    startDate: '12/01/2007',
    zipCode: '10010',
    department: 'Human Resources',
    state: 'NY, New York',
  },
  {
    firstName: 'Ethan',
    lastName: 'Anderson',
    street: '1313 Maple Avenue',
    city: 'Seattle',
    dateOfBirth: '07/11/1997',
    startDate: '11/01/2019',
    zipCode: '98110',
    department: 'Marketing',
    state: 'WA, Washington',
  },
  {
    firstName: 'Liam',
    lastName: 'Wilson',
    street: '789 Oak Street',
    city: 'Chicago',
    dateOfBirth: '02/06/1989',
    startDate: '10/01/2011',
    zipCode: '60611',
    department: 'Sales',
    state: 'IL, Illinois',
  },
  {
    firstName: 'Avery',
    lastName: 'Miller',
    street: '1011 Pine Avenue',
    city: 'Dallas',
    dateOfBirth: '09/09/2000',
    startDate: '09/01/2022',
    zipCode: '75210',
    department: 'Engineering',
    state: 'TX, Texas',
  },
  {
    firstName: 'Charlotte',
    lastName: 'Robinson',
    street: '1313 Walnut Street',
    city: 'Miami',
    dateOfBirth: '08/23/1981',
    startDate: '08/01/2003',
    zipCode: '33110',
    department: 'Human Resources',
    state: 'FL, Florida',
  },
  {
    firstName: 'Henry',
    lastName: 'Parker',
    street: '789 Cedar Avenue',
    city: 'Boston',
    dateOfBirth: '01/27/1993',
    startDate: '07/01/2015',
    zipCode: '02110',
    department: 'Sales',
    state: 'MA, Massachusetts',
  },
  {
    firstName: 'Ella',
    lastName: 'Gonzalez',
    street: '456 Oak Street',
    city: 'Los Angeles',
    dateOfBirth: '06/01/2005',
    startDate: '06/01/2027',
    zipCode: '90014',
    department: 'Engineering',
    state: 'CA, California',
  },
  {
    firstName: 'Oliver',
    lastName: 'Young',
    street: '1011 Elm Street',
    city: 'New York',
    dateOfBirth: '11/14/1986',
    startDate: '05/01/2008',
    zipCode: '10011',
    department: 'Human Resources',
    state: 'NY, New York',
  },
  {
    firstName: 'Scarlett',
    lastName: 'Anderson',
    street: '1313 Maple Avenue',
    city: 'Seattle',
    dateOfBirth: '07/10/1998',
    startDate: '04/01/2020',
    zipCode: '98111',
    department: 'Marketing',
    state: 'WA, Washington',
  },
  {
    firstName: 'Jackson',
    lastName: 'Wilson',
    street: '789 Oak Street',
    city: 'Chicago',
    dateOfBirth: '02/05/1990',
    startDate: '03/01/2012',
    zipCode: '60612',
    department: 'Sales',
    state: 'IL, Illinois',
  },
  {
    firstName: 'Sophia',
    lastName: 'Miller',
    street: '1011 Pine Avenue',
    city: 'Dallas',
    dateOfBirth: '09/08/2001',
    startDate: '02/01/2023',
    zipCode: '75211',
    department: 'Engineering',
    state: 'TX, Texas',
  },
  {
    firstName: 'Luna',
    lastName: 'Robinson',
    street: '1313 Walnut Street',
    city: 'Miami',
    dateOfBirth: '08/22/1982',
    startDate: '01/01/2005',
    zipCode: '33112',
    department: 'Human Resources',
    state: 'FL, Florida',
  },
  {
    firstName: 'Caleb',
    lastName: 'Parker',
    street: '789 Cedar Avenue',
    city: 'Boston',
    dateOfBirth: '01/26/1994',
    startDate: '12/01/2016',
    zipCode: '02111',
    department: 'Sales',
    state: 'MA, Massachusetts',
  },
  {
    firstName: 'Elena',
    lastName: 'Gonzalez',
    street: '456 Oak Street',
    city: 'Los Angeles',
    dateOfBirth: '05/31/2006',
    startDate: '11/01/2028',
    zipCode: '90015',
    department: 'Engineering',
    state: 'CA, California',
  },
  {
    firstName: 'James',
    lastName: 'Young',
    street: '1011 Elm Street',
    city: 'New York',
    dateOfBirth: '11/13/1987',
    startDate: '10/01/2009',
    zipCode: '10012',
    department: 'Human Resources',
    state: 'NY, New York',
  },
  {
    firstName: 'Avery',
    lastName: 'Anderson',
    street: '1313 Maple Avenue',
    city: 'Seattle',
    dateOfBirth: '07/09/1999',
    startDate: '09/01/2021',
    zipCode: '98112',
    department: 'Marketing',
    state: 'WA, Washington',
  },
  {
    firstName: 'Benjamin',
    lastName: 'Lewis',
    street: '789 Oak Street',
    city: 'Chicago',
    dateOfBirth: '02/04/1991',
    startDate: '08/01/2013',
    zipCode: '60613',
    department: 'Sales',
    state: 'IL, Illinois',
  },
  {
    firstName: 'Layla',
    lastName: 'Taylor',
    street: '1011 Pine Avenue',
    city: 'Dallas',
    dateOfBirth: '09/07/2002',
    startDate: '07/01/2024',
    zipCode: '75212',
    department: 'Engineering',
    state: 'TX, Texas',
  },
  {
    firstName: 'Lucas',
    lastName: 'Robinson',
    street: '1313 Walnut Street',
    city: 'Miami',
    dateOfBirth: '08/21/1983',
    startDate: '06/01/2005',
    zipCode: '33113',
    department: 'Human Resources',
    state: 'FL, Florida',
  },
  {
    firstName: 'Zoey',
    lastName: 'Parker',
    street: '789 Cedar Avenue',
    city: 'Boston',
    dateOfBirth: '01/25/1995',
    startDate: '05/01/2017',
    zipCode: '02112',
    department: 'Sales',
    state: 'MA, Massachusetts',
  },
  {
    firstName: 'Matthew',
    lastName: 'Gonzalez',
    street: '456 Oak Street',
    city: 'Los Angeles',
    dateOfBirth: '05/30/2007',
    startDate: '04/01/2029',
    zipCode: '90016',
    department: 'Engineering',
    state: 'CA, California',
  },
  {
    firstName: 'Avery',
    lastName: 'Young',
    street: '1011 Elm Street',
    city: 'New York',
    dateOfBirth: '11/12/1988',
    startDate: '03/01/2010',
    zipCode: '10013',
    department: 'Human Resources',
    state: 'NY, New York',
  },
  {
    firstName: 'Julian',
    lastName: 'Anderson',
    street: '1313 Maple Avenue',
    city: 'Seattle',
    dateOfBirth: '07/08/2000',
    startDate: '02/01/2022',
    zipCode: '98114',
    department: 'Marketing',
    state: 'WA, Washington',
  },
  {
    firstName: 'Daniel',
    lastName: 'Wilson',
    street: '789 Oak Street',
    city: 'Chicago',
    dateOfBirth: '02/03/1992',
    startDate: '01/01/2014',
    zipCode: '60614',
    department: 'Sales',
    state: 'IL, Illinois',
  },
  {
    firstName: 'Nora',
    lastName: 'Miller',
    street: '1011 Pine Avenue',
    city: 'Dallas',
    dateOfBirth: '09/06/2003',
    startDate: '12/01/2025',
    zipCode: '75213',
    department: 'Engineering',
    state: 'TX, Texas',
  },
  {
    firstName: 'Eva',
    lastName: 'Robinson',
    street: '1313 Walnut Street',
    city: 'Miami',
    dateOfBirth: '08/20/1984',
    startDate: '11/01/2006',
    zipCode: '33115',
    department: 'Human Resources',
    state: 'FL, Florida',
  },
  {
    firstName: 'Henry',
    lastName: 'Parker',
    street: '789 Cedar Avenue',
    city: 'Boston',
    dateOfBirth: '01/24/1996',
    startDate: '10/01/2018',
    zipCode: '02113',
    department: 'Sales',
    state: 'MA, Massachusetts',
  },
  {
    firstName: 'Aria',
    lastName: 'Gonzalez',
    street: '456 Oak Street',
    city: 'Los Angeles',
    dateOfBirth: '05/29/2008',
    startDate: '09/01/2030',
    zipCode: '90017',
    department: 'Engineering',
    state: 'CA, California',
  },
  {
    firstName: 'Mila',
    lastName: 'Young',
    street: '1011 Elm Street',
    city: 'New York',
    dateOfBirth: '11/11/1989',
    startDate: '08/01/2011',
    zipCode: '10014',
    department: 'Human Resources',
    state: 'NY, New York',
  },
  {
    firstName: 'Liam',
    lastName: 'Anderson',
    street: '1313 Maple Avenue',
    city: 'Seattle',
    dateOfBirth: '07/07/2001',
    startDate: '07/01/2023',
    zipCode: '98115',
    department: 'Marketing',
    state: 'WA, Washington',
  },
  {
    firstName: 'Lucy',
    lastName: 'Wilson',
    street: '789 Oak Street',
    city: 'Chicago',
    dateOfBirth: '02/02/1993',
    startDate: '06/01/2015',
    zipCode: '60615',
    department: 'Sales',
    state: 'IL, Illinois',
  },
  {
    firstName: 'Jackson',
    lastName: 'Miller',
    street: '1011 Pine Avenue',
    city: 'Dallas',
    dateOfBirth: '09/05/2004',
    startDate: '05/01/2027',
    zipCode: '75214',
    department: 'Engineering',
    state: 'TX, Texas',
  },
  {
    firstName: 'Harper',
    lastName: 'Robinson',
    street: '1313 Walnut Street',
    city: 'Miami',
    dateOfBirth: '08/19/1985',
    startDate: '04/01/2007',
    zipCode: '33116',
    department: 'Human Resources',
    state: 'FL, Florida',
  },
  {
    firstName: 'Ethan',
    lastName: 'Parker',
    street: '789 Cedar Avenue',
    city: 'Boston',
    dateOfBirth: '01/23/1997',
    startDate: '03/01/2019',
    zipCode: '02114',
    department: 'Sales',
    state: 'MA, Massachusetts',
  },
  {
    firstName: 'Lily',
    lastName: 'Gonzalez',
    street: '456 Oak Street',
    city: 'Los Angeles',
    dateOfBirth: '05/28/2009',
    startDate: '02/01/2031',
    zipCode: '90018',
    department: 'Engineering',
    state: 'CA, California',
  },
  {
    firstName: 'Oliver',
    lastName: 'Young',
    street: '1011 Elm Street',
    city: 'New York',
    dateOfBirth: '11/10/1990',
    startDate: '01/01/2012',
    zipCode: '10015',
    department: 'Human Resources',
    state: 'NY, New York',
  },
  {
    firstName: 'Amelia',
    lastName: 'Anderson',
    street: '1313 Maple Avenue',
    city: 'Seattle',
    dateOfBirth: '07/06/2002',
    startDate: '12/01/2023',
    zipCode: '98116',
    department: 'Marketing',
    state: 'WA, Washington',
  },
  {
    firstName: 'Alexander',
    lastName: 'Wilson',
    street: '789 Oak Street',
    city: 'Chicago',
    dateOfBirth: '02/01/1994',
    startDate: '11/01/2015',
    zipCode: '60616',
    department: 'Sales',
    state: 'IL, Illinois',
  },
  {
    firstName: 'Avery',
    lastName: 'Miller',
    street: '1011 Pine Avenue',
    city: 'Dallas',
    dateOfBirth: '09/04/2005',
    startDate: '10/01/2027',
    zipCode: '75215',
    department: 'Engineering',
    state: 'TX, Texas',
  },
  {
    firstName: 'Mia',
    lastName: 'Robinson',
    street: '1313 Walnut Street',
    city: 'Miami',
    dateOfBirth: '08/18/1986',
    startDate: '09/01/2008',
    zipCode: '33117',
    department: 'Human Resources',
    state: 'FL, Florida',
  },
  {
    firstName: 'Sebastian',
    lastName: 'Parker',
    street: '789 Cedar Avenue',
    city: 'Boston',
    dateOfBirth: '01/22/1998',
    startDate: '08/01/2020',
    zipCode: '02115',
    department: 'Sales',
    state: 'MA, Massachusetts',
  },
  {
    firstName: 'Ava',
    lastName: 'Gonzalez',
    street: '456 Oak Street',
    city: 'Los Angeles',
    dateOfBirth: '05/27/2010',
    startDate: '07/01/2032',
    zipCode: '90019',
    department: 'Engineering',
    state: 'CA, California',
  },
  {
    firstName: 'Elijah',
    lastName: 'Young',
    street: '1011 Elm Street',
    city: 'New York',
    dateOfBirth: '11/09/1991',
    startDate: '06/01/2013',
    zipCode: '10016',
    department: 'Human Resources',
    state: 'NY, New York',
  },
  {
    firstName: 'Layla',
    lastName: 'Anderson',
    street: '1313 Maple Avenue',
    city: 'Seattle',
    dateOfBirth: '07/05/2003',
    startDate: '05/01/2025',
    zipCode: '98117',
    department: 'Marketing',
    state: 'WA, Washington',
  },
  {
    firstName: 'Mason',
    lastName: 'Wilson',
    street: '789 Oak Street',
    city: 'Chicago',
    dateOfBirth: '01/31/1995',
    startDate: '04/01/2017',
    zipCode: '60617',
    department: 'Sales',
    state: 'IL, Illinois',
  },
  {
    firstName: 'Penelope',
    lastName: 'Miller',
    street: '1011 Pine Avenue',
    city: 'Dallas',
    dateOfBirth: '09/03/2006',
    startDate: '03/01/2029',
    zipCode: '75216',
    department: 'Engineering',
    state: 'TX, Texas',
  },
  {
    firstName: 'Scarlett',
    lastName: 'Robinson',
    street: '1313 Walnut Street',
    city: 'Miami',
    dateOfBirth: '08/17/1987',
    startDate: '02/01/2009',
    zipCode: '33118',
    department: 'Human Resources',
    state: 'FL, Florida',
  },
  {
    firstName: 'Ryan',
    lastName: 'Parker',
    street: '789 Cedar Avenue',
    city: 'Boston',
    dateOfBirth: '01/21/1999',
    startDate: '01/01/2021',
    zipCode: '02116',
    department: 'Sales',
    state: 'MA, Massachusetts',
  },
  {
    firstName: 'Aria',
    lastName: 'Gonzalez',
    street: '456 Oak Street',
    city: 'Los Angeles',
    dateOfBirth: '05/26/2011',
    startDate: '12/01/2033',
    zipCode: '90020',
    department: 'Engineering',
    state: 'CA, California',
  },
  {
    firstName: 'Noah',
    lastName: 'Young',
    street: '1011 Elm Street',
    city: 'New York',
    dateOfBirth: '11/08/1992',
    startDate: '11/01/2014',
    zipCode: '10017',
    department: 'Human Resources',
    state: 'NY, New York',
  },
  {
    firstName: 'Emma',
    lastName: 'Anderson',
    street: '1313 Maple Avenue',
    city: 'Seattle',
    dateOfBirth: '07/04/2004',
    startDate: '10/01/2026',
    zipCode: '98118',
    department: 'Marketing',
    state: 'WA, Washington',
  },
  {
    firstName: 'William',
    lastName: 'Wilson',
    street: '789 Oak Street',
    city: 'Chicago',
    dateOfBirth: '01/30/1996',
    startDate: '09/01/2018',
    zipCode: '60618',
    department: 'Sales',
    state: 'IL, Illinois',
  },
  {
    firstName: 'Grace',
    lastName: 'Miller',
    street: '1011 Pine Avenue',
    city: 'Dallas',
    dateOfBirth: '09/02/2007',
    startDate: '08/01/2030',
    zipCode: '75217',
    department: 'Engineering',
    state: 'TX, Texas',
  },
  {
    firstName: 'Jack',
    lastName: 'Robinson',
    street: '1313 Walnut Street',
    city: 'Miami',
    dateOfBirth: '08/16/1988',
    startDate: '07/01/2010',
    zipCode: '33119',
    department: 'Human Resources',
    state: 'FL, Florida',
  },
  {
    firstName: 'Sofia',
    lastName: 'Parker',
    street: '789 Cedar Avenue',
    city: 'Boston',
    dateOfBirth: '01/20/2000',
    startDate: '06/01/2022',
    zipCode: '02117',
    department: 'Sales',
    state: 'MA, Massachusetts',
  },
  {
    firstName: 'Evelyn',
    lastName: 'Gonzalez',
    street: '456 Oak Street',
    city: 'Los Angeles',
    dateOfBirth: '05/25/2012',
    startDate: '05/01/2034',
    zipCode: '90021',
    department: 'Engineering',
    state: 'CA, California',
  },
  {
    firstName: 'Daniel',
    lastName: 'Young',
    street: '1011 Elm Street',
    city: 'New York',
    dateOfBirth: '11/07/1993',
    startDate: '04/01/2015',
    zipCode: '10018',
    department: 'Human Resources',
    state: 'NY, New York',
  },
  {
    firstName: 'Victoria',
    lastName: 'Anderson',
    street: '1313 Maple Avenue',
    city: 'Seattle',
    dateOfBirth: '07/03/2005',
    startDate: '03/01/2027',
    zipCode: '98119',
    department: 'Marketing',
    state: 'WA, Washington',
  },
  {
    firstName: 'Michael',
    lastName: 'Wilson',
    street: '789 Oak Street',
    city: 'Chicago',
    dateOfBirth: '01/29/1997',
    startDate: '02/01/2019',
    zipCode: '60619',
    department: 'Sales',
    state: 'IL, Illinois',
  },
  {
    firstName: 'Sophia',
    lastName: 'Miller',
    street: '1011 Pine Avenue',
    city: 'Dallas',
    dateOfBirth: '09/01/2008',
    startDate: '01/01/2031',
    zipCode: '75218',
    department: 'Engineering',
    state: 'TX, Texas',
  },
  {
    firstName: 'James',
    lastName: 'Robinson',
    street: '1313 Walnut Street',
    city: 'Miami',
    dateOfBirth: '08/15/1989',
    startDate: '12/01/2011',
    zipCode: '33120',
    department: 'Human Resources',
    state: 'FL, Florida',
  },
  {
    firstName: 'Madison',
    lastName: 'Parker',
    street: '789 Cedar Avenue',
    city: 'Boston',
    dateOfBirth: '01/19/2001',
    startDate: '11/01/2022',
    zipCode: '02118',
    department: 'Sales',
    state: 'MA, Massachusetts',
  },
  {
    firstName: 'Abigail',
    lastName: 'Gonzalez',
    street: '456 Oak Street',
    city: 'Los Angeles',
    dateOfBirth: '05/24/2013',
    startDate: '10/01/2035',
    zipCode: '90022',
    department: 'Engineering',
    state: 'CA, California',
  },
  {
    firstName: 'David',
    lastName: 'Young',
    street: '1011 Elm Street',
    city: 'New York',
    dateOfBirth: '11/06/1994',
    startDate: '09/01/2016',
    zipCode: '10019',
    department: 'Human Resources',
    state: 'NY, New York',
  },
  {
    firstName: 'Joseph',
    lastName: 'Anderson',
    street: '1313 Maple Avenue',
    city: 'Seattle',
    dateOfBirth: '07/02/2006',
    startDate: '08/01/2028',
    zipCode: '98120',
    department: 'Marketing',
    state: 'WA, Washington',
  },
  {
    firstName: 'Henry',
    lastName: 'Wilson',
    street: '789 Oak Street',
    city: 'Chicago',
    dateOfBirth: '01/28/1998',
    startDate: '07/01/2020',
    zipCode: '60620',
    department: 'Sales',
    state: 'IL, Illinois',
  },
  {
    firstName: 'Elizabeth',
    lastName: 'Miller',
    street: '1011 Pine Avenue',
    city: 'Dallas',
    dateOfBirth: '08/31/2009',
    startDate: '06/01/2032',
    zipCode: '75219',
    department: 'Engineering',
    state: 'TX, Texas',
  },
  {
    firstName: 'Benjamin',
    lastName: 'Robinson',
    street: '1313 Walnut Street',
    city: 'Miami',
    dateOfBirth: '08/14/1990',
    startDate: '05/01/2012',
    zipCode: '33121',
    department: 'Human Resources',
    state: 'FL, Florida',
  },
  {
    firstName: 'Avery',
    lastName: 'Parker',
    street: '789 Cedar Avenue',
    city: 'Boston',
    dateOfBirth: '01/18/2002',
    startDate: '04/01/2024',
    zipCode: '02119',
    department: 'Sales',
    state: 'MA, Massachusetts',
  },
  {
    firstName: 'Charlotte',
    lastName: 'Gonzalez',
    street: '456 Oak Street',
    city: 'Los Angeles',
    dateOfBirth: '05/23/2014',
    startDate: '03/01/2036',
    zipCode: '90023',
    department: 'Engineering',
    state: 'CA, California',
  },
  {
    firstName: 'Andrew',
    lastName: 'Young',
    street: '1011 Elm Street',
    city: 'New York',
    dateOfBirth: '11/05/1995',
    startDate: '02/01/2017',
    zipCode: '10020',
    department: 'Human Resources',
    state: 'NY, New York',
  },
  {
    firstName: 'Mila',
    lastName: 'Anderson',
    street: '1313 Maple Avenue',
    city: 'Seattle',
    dateOfBirth: '07/01/2007',
    startDate: '01/01/2029',
    zipCode: '98121',
    department: 'Marketing',
    state: 'WA, Washington',
  },
  {
    firstName: 'Owen',
    lastName: 'Wilson',
    street: '789 Oak Street',
    city: 'Chicago',
    dateOfBirth: '01/27/1999',
    startDate: '12/01/2020',
    zipCode: '60621',
    department: 'Sales',
    state: 'IL, Illinois',
  },
  {
    firstName: 'Lillian',
    lastName: 'Miller',
    street: '1011 Pine Avenue',
    city: 'Dallas',
    dateOfBirth: '08/30/2010',
    startDate: '11/01/2033',
    zipCode: '75220',
    department: 'Engineering',
    state: 'TX, Texas',
  },
  {
    firstName: 'Matthew',
    lastName: 'Robinson',
    street: '1313 Walnut Street',
    city: 'Miami',
    dateOfBirth: '08/13/1991',
    startDate: '10/01/2013',
    zipCode: '33122',
    department: 'Human Resources',
    state: 'FL, Florida',
  },
  {
    firstName: 'Harper',
    lastName: 'Parker',
    street: '789 Cedar Avenue',
    city: 'Boston',
    dateOfBirth: '01/17/2003',
    startDate: '09/01/2025',
    zipCode: '02120',
    department: 'Sales',
    state: 'MA, Massachusetts',
  },
  {
    firstName: 'Ella',
    lastName: 'Gonzalez',
    street: '456 Oak Street',
    city: 'Los Angeles',
    dateOfBirth: '05/22/2015',
    startDate: '08/01/2037',
    zipCode: '90024',
    department: 'Engineering',
    state: 'CA, California',
  },
  {
    firstName: 'Christopher',
    lastName: 'Young',
    street: '1011 Elm Street',
    city: 'New York',
    dateOfBirth: '11/04/1996',
    startDate: '07/01/2018',
    zipCode: '10021',
    department: 'Human Resources',
    state: 'NY, New York',
  },
  {
    firstName: 'Victoria',
    lastName: 'Anderson',
    street: '1313 Maple Avenue',
    city: 'Seattle',
    dateOfBirth: '06/30/2008',
    startDate: '06/01/2030',
    zipCode: '98122',
    department: 'Marketing',
    state: 'WA, Washington',
  },
  {
    firstName: 'Joseph',
    lastName: 'Wilson',
    street: '789 Oak Street',
    city: 'Chicago',
    dateOfBirth: '01/26/2000',
    startDate: '05/01/2022',
    zipCode: '60622',
    department: 'Sales',
    state: 'IL, Illinois',
  },
  {
    firstName: 'Avery',
    lastName: 'Miller',
    street: '1011 Pine Avenue',
    city: 'Dallas',
    dateOfBirth: '08/29/2011',
    startDate: '04/01/2034',
    zipCode: '75221',
    department: 'Engineering',
    state: 'TX, Texas',
  },
  {
    firstName: 'Scarlett',
    lastName: 'Robinson',
    street: '1313 Walnut Street',
    city: 'Miami',
    dateOfBirth: '08/12/1992',
    startDate: '03/01/2014',
    zipCode: '33123',
    department: 'Human Resources',
    state: 'FL, Florida',
  },
  {
    firstName: 'Evelyn',
    lastName: 'Parker',
    street: '789 Cedar Avenue',
    city: 'Boston',
    dateOfBirth: '01/16/2004',
    startDate: '02/01/2026',
    zipCode: '02121',
    department: 'Sales',
    state: 'MA, Massachusetts',
  },
  {
    firstName: 'Lucas',
    lastName: 'Gonzalez',
    street: '456 Oak Street',
    city: 'Los Angeles',
    dateOfBirth: '05/21/2016',
    startDate: '01/01/2038',
    zipCode: '90025',
    department: 'Engineering',
    state: 'CA, California',
  },
  {
    firstName: 'Daniel',
    lastName: 'Young',
    street: '1011 Elm Street',
    city: 'New York',
    dateOfBirth: '11/03/1997',
    startDate: '12/01/2019',
    zipCode: '10022',
    department: 'Human Resources',
    state: 'NY, New York',
  },
  {
    firstName: 'Sofia',
    lastName: 'Anderson',
    street: '1313 Maple Avenue',
    city: 'Seattle',
    dateOfBirth: '06/29/2009',
    startDate: '11/01/2031',
    zipCode: '98123',
    department: 'Marketing',
    state: 'WA, Washington',
  },
  {
    firstName: 'Carter',
    lastName: 'Wilson',
    street: '789 Oak Street',
    city: 'Chicago',
    dateOfBirth: '01/25/2001',
    startDate: '10/01/2023',
    zipCode: '60623',
    department: 'Sales',
    state: 'IL, Illinois',
  },
  {
    firstName: 'Aria',
    lastName: 'Miller',
    street: '1011 Pine Avenue',
    city: 'Dallas',
    dateOfBirth: '08/28/2012',
    startDate: '09/01/2035',
    zipCode: '75222',
    department: 'Engineering',
    state: 'TX, Texas',
  },
  {
    firstName: 'Benjamin',
    lastName: 'Robinson',
    street: '1313 Walnut Street',
    city: 'Miami',
    dateOfBirth: '08/11/1993',
    startDate: '08/01/2015',
    zipCode: '33124',
    department: 'Human Resources',
    state: 'FL, Florida',
  },
  {
    firstName: 'Mila',
    lastName: 'Parker',
    street: '789 Cedar Avenue',
    city: 'Boston',
    dateOfBirth: '01/15/2005',
    startDate: '07/01/2027',
    zipCode: '02122',
    department: 'Sales',
    state: 'MA, Massachusetts',
  },
];

export default employees;
