const employees = [
  {
    firstName: 'LeBron',
    lastName: 'James',
    street: '123 Main Street',
    city: 'Los Angeles',
    dateOfBirth: '12/30/1984',
    startDate: '07/01/2003',
    zipCode: '90001',
    department: 'California',
    state: 'USA',
  },
  {
    firstName: 'Serena',
    lastName: 'Williams',
    street: '456 Elm Avenue',
    city: 'Miami',
    dateOfBirth: '09/26/1981',
    startDate: '09/24/1995',
    zipCode: '33101',
    department: 'Florida',
    state: 'USA',
  },
  {
    firstName: 'Lionel',
    lastName: 'Messi',
    street: '15 Cherry Street',
    city: 'Barcelona',
    dateOfBirth: '06/24/1987',
    startDate: '08/01/2004',
    zipCode: '08001',
    department: 'Barcelona',
    state: 'Spain',
  },
  {
    firstName: 'Naomi',
    lastName: 'Osaka',
    street: '20 Pine Street',
    city: 'Tokyo',
    dateOfBirth: '10/16/1997',
    startDate: '09/01/2013',
    zipCode: '100-0001',
    department: 'Tokyo',
    state: 'Japan',
  },
  {
    firstName: 'Roger',
    lastName: 'Federer',
    street: '35 Willow Street',
    city: 'Basel',
    dateOfBirth: '08/08/1981',
    startDate: '07/01/1998',
    zipCode: '4001',
    department: 'Basel-Stadt',
    state: 'Switzerland',
  },
  {
    firstName: 'Rafael',
    lastName: 'Nadal',
    street: '45 Maple Avenue',
    city: 'Mallorca',
    dateOfBirth: '06/03/1986',
    startDate: '01/01/2001',
    zipCode: '07001',
    department: 'Balearic Islands',
    state: 'Spain',
  },
  {
    firstName: 'Lewis',
    lastName: 'Hamilton',
    street: '55 Oak Lane',
    city: 'London',
    dateOfBirth: '01/07/1985',
    startDate: '01/01/2007',
    zipCode: 'SW1A 1AA',
    department: 'Greater London',
    state: 'UK',
  },
  {
    firstName: 'Sachin',
    lastName: 'Tendulkar',
    street: '60 Maple Road',
    city: 'Mumbai',
    dateOfBirth: '04/24/1973',
    startDate: '12/18/1989',
    zipCode: '400001',
    department: 'Maharashtra',
    state: 'India',
  },
  {
    firstName: 'Simona',
    lastName: 'Halep',
    street: '65 Cherry Street',
    city: 'Constanta',
    dateOfBirth: '09/27/1991',
    startDate: '01/01/2006',
    zipCode: '900001',
    department: 'Constanta',
    state: 'Romania',
  },
  {
    firstName: 'Tom',
    lastName: 'Brady',
    street: '70 Pine Avenue',
    city: 'Tampa',
    dateOfBirth: '08/03/1977',
    startDate: '09/23/2000',
    zipCode: '33601',
    department: 'Florida',
    state: 'USA',
  },
  {
    firstName: 'Maria',
    lastName: 'Sharapova',
    street: '75 Oak Street',
    city: 'Moscow',
    dateOfBirth: '04/19/1987',
    startDate: '01/01/2001',
    zipCode: '101000',
    department: 'Moscow',
    state: 'Russia',
  },
  {
    firstName: 'Stephen',
    lastName: 'Curry',
    street: '80 Maple Road',
    city: 'San Francisco',
    dateOfBirth: '03/14/1988',
    startDate: '07/01/2009',
    zipCode: '94101',
    department: 'California',
    state: 'USA',
  },
  {
    firstName: 'Caroline',
    lastName: 'Wozniacki',
    street: '85 Cherry Avenue',
    city: 'Copenhagen',
    dateOfBirth: '07/11/1990',
    startDate: '07/18/2005',
    zipCode: '1050',
    department: 'Copenhagen',
    state: 'Denmark',
  },
  {
    firstName: 'Kobe',
    lastName: 'Bryant',
    street: '90 Pine Street',
    city: 'Los Angeles',
    dateOfBirth: '08/23/1978',
    startDate: '11/03/1996',
    zipCode: '90001',
    department: 'California',
    state: 'USA',
  },
  {
    firstName: 'Venus',
    lastName: 'Williams',
    street: '95 Oak Lane',
    city: 'Palm Beach Gardens',
    dateOfBirth: '06/17/1980',
    startDate: '10/31/1994',
    zipCode: '33418',
    department: 'Florida',
    state: 'USA',
  },
  {
    firstName: 'Novak',
    lastName: 'Djokovic',
    street: '100 Maple Avenue',
    city: 'Belgrade',
    dateOfBirth: '05/22/1987',
    startDate: '01/01/2003',
    zipCode: '11000',
    department: 'Belgrade',
    state: 'Serbia',
  },
  {
    firstName: 'Katie',
    lastName: 'Ledecky',
    street: '105 Cherry Street',
    city: 'Washington, D.C.',
    dateOfBirth: '03/17/1997',
    startDate: '01/01/2012',
    zipCode: '20001',
    department: 'District of Columbia',
    state: 'USA',
  },
  {
    firstName: 'Michael',
    lastName: 'Jordan',
    street: '110 Oak Lane',
    city: 'Chicago',
    dateOfBirth: '02/17/1963',
    startDate: '10/26/1984',
    zipCode: '60601',
    department: 'Illinois',
    state: 'USA',
  },
  {
    firstName: 'Marta',
    lastName: 'Vieira',
    street: '115 Maple Road',
    city: 'Orlando',
    dateOfBirth: '02/19/1986',
    startDate: '01/01/2002',
    zipCode: '32801',
    department: 'Florida',
    state: 'USA',
  },
  {
    firstName: 'Zlatan',
    lastName: 'Ibrahimović',
    street: '120 Pine Avenue',
    city: 'Milan',
    dateOfBirth: '10/03/1981',
    startDate: '01/01/1999',
    zipCode: '20121',
    department: 'Milan',
    state: 'Italy',
  },
  {
    firstName: 'Lindsey',
    lastName: 'Vonn',
    street: '125 Oak Street',
    city: 'Vail',
    dateOfBirth: '10/18/1984',
    startDate: '01/01/2000',
    zipCode: '81657',
    department: 'Colorado',
    state: 'USA',
  },
  {
    firstName: 'Andre',
    lastName: 'Agassi',
    street: '130 Maple Avenue',
    city: 'Las Vegas',
    dateOfBirth: '04/29/1970',
    startDate: '01/01/1986',
    zipCode: '89101',
    department: 'Nevada',
    state: 'USA',
  },
  {
    firstName: 'Megan',
    lastName: 'Rapinoe',
    street: '135 Cherry Street',
    city: 'Seattle',
    dateOfBirth: '07/05/1985',
    startDate: '01/01/2002',
    zipCode: '98101',
    department: 'Washington',
    state: 'USA',
  },
  {
    firstName: 'Rory',
    lastName: 'McIlroy',
    street: '140 Oak Lane',
    city: 'Hollywood',
    dateOfBirth: '05/04/1989',
    startDate: '01/01/2005',
    zipCode: '33021',
    department: 'Florida',
    state: 'USA',
  },
  {
    firstName: 'Danica',
    lastName: 'Patrick',
    street: '145 Maple Road',
    city: 'Indianapolis',
    dateOfBirth: '03/25/1982',
    startDate: '01/01/2002',
    zipCode: '46201',
    department: 'Indiana',
    state: 'USA',
  },
  {
    firstName: 'Rafael',
    lastName: 'Marquez',
    street: '150 Pine Avenue',
    city: 'Mexico City',
    dateOfBirth: '02/13/1979',
    startDate: '01/01/1996',
    zipCode: '06000',
    department: 'Mexico City',
    state: 'Mexico',
  },
  {
    firstName: 'Neymar',
    lastName: 'Jr.',
    street: '155 Oak Street',
    city: 'Paris',
    dateOfBirth: '02/05/1992',
    startDate: '01/01/2009',
    zipCode: '75001',
    department: 'Paris',
    state: 'France',
  },
  {
    firstName: 'Sania',
    lastName: 'Mirza',
    street: '160 Maple Avenue',
    city: 'Hyderabad',
    dateOfBirth: '11/15/1986',
    startDate: '01/01/2003',
    zipCode: '500001',
    department: 'Telangana',
    state: 'India',
  },
  {
    firstName: 'Wayne',
    lastName: 'Gretzky',
    street: '165 Cherry Street',
    city: 'Edmonton',
    dateOfBirth: '01/26/1961',
    startDate: '01/01/1979',
    zipCode: 'T5J 0H6',
    department: 'Alberta',
    state: 'Canada',
  },
  {
    firstName: 'Sergio',
    lastName: 'Ramos',
    street: '170 Oak Lane',
    city: 'Madrid',
    dateOfBirth: '03/30/1986',
    startDate: '08/01/2004',
    zipCode: '28001',
    department: 'Madrid',
    state: 'Spain',
  },
  {
    firstName: 'Gabrielle',
    lastName: 'Douglas',
    street: '175 Maple Road',
    city: 'Los Angeles',
    dateOfBirth: '12/31/1995',
    startDate: '01/01/2010',
    zipCode: '90001',
    department: 'California',
    state: 'USA',
  },
  {
    firstName: 'Chris',
    lastName: 'Froome',
    street: '180 Pine Avenue',
    city: 'Nairobi',
    dateOfBirth: '05/20/1985',
    startDate: '01/01/2007',
    zipCode: '00100',
    department: 'Nairobi',
    state: 'Kenya',
  },
  {
    firstName: 'Gabby',
    lastName: 'Williams',
    street: '185 Oak Street',
    city: 'Las Vegas',
    dateOfBirth: '09/09/1996',
    startDate: '01/01/2018',
    zipCode: '89101',
    department: 'Nevada',
    state: 'USA',
  },
  {
    firstName: 'Babe',
    lastName: 'Ruth',
    street: '190 Maple Avenue',
    city: 'New York',
    dateOfBirth: '02/06/1895',
    startDate: '07/11/1914',
    zipCode: '10001',
    department: 'New York',
    state: 'USA',
  },
  {
    firstName: 'Carli',
    lastName: 'Lloyd',
    street: '195 Cherry Street',
    city: 'Delran',
    dateOfBirth: '07/16/1982',
    startDate: '01/01/2005',
    zipCode: '08075',
    department: 'New Jersey',
    state: 'USA',
  },
  {
    firstName: 'Andre',
    lastName: 'Drummond',
    street: '200 Oak Lane',
    city: 'New York',
    dateOfBirth: '08/10/1993',
    startDate: '01/01/2012',
    zipCode: '10001',
    department: 'New York',
    state: 'USA',
  },
  {
    firstName: 'Sania',
    lastName: 'Nehwal',
    street: '205 Maple Road',
    city: 'Hyderabad',
    dateOfBirth: '03/17/1990',
    startDate: '01/01/2003',
    zipCode: '500001',
    department: 'Telangana',
    state: 'India',
  },
  {
    firstName: 'Jerry',
    lastName: 'Rice',
    street: '210 Pine Avenue',
    city: 'San Francisco',
    dateOfBirth: '10/13/1962',
    startDate: '08/01/1985',
    zipCode: '94101',
    department: 'California',
    state: 'USA',
  },
  {
    firstName: 'Helen',
    lastName: 'Glover',
    street: '215 Oak Street',
    city: 'Penryn',
    dateOfBirth: '06/17/1986',
    startDate: '01/01/2008',
    zipCode: 'TR10 8RF',
    department: 'Cornwall',
    state: 'UK',
  },
  {
    firstName: 'Alex',
    lastName: 'Morgan',
    street: '220 Maple Avenue',
    city: 'San Dimas',
    dateOfBirth: '07/02/1989',
    startDate: '01/01/2010',
    zipCode: '91773',
    department: 'California',
    state: 'USA',
  },
  {
    firstName: 'Dwayne',
    lastName: 'Wade',
    street: '225 Cherry Street',
    city: 'Miami',
    dateOfBirth: '01/17/1982',
    startDate: '01/01/2003',
    zipCode: '33101',
    department: 'Florida',
    state: 'USA',
  },
  {
    firstName: 'Christiano',
    lastName: 'Ronaldo',
    street: '230 Oak Lane',
    city: 'Funchal',
    dateOfBirth: '02/05/1985',
    startDate: '01/01/2002',
    zipCode: '9000',
    department: 'Madeira',
    state: 'Portugal',
  },
  {
    firstName: 'Hope',
    lastName: 'Solo',
    street: '235 Maple Road',
    city: 'Richland',
    dateOfBirth: '07/30/1981',
    startDate: '01/01/2000',
    zipCode: '99352',
    department: 'Washington',
    state: 'USA',
  },
  {
    firstName: 'Usain',
    lastName: 'Bolt',
    street: '240 Pine Avenue',
    city: 'Kingston',
    dateOfBirth: '08/21/1986',
    startDate: '01/01/2004',
    zipCode: '876',
    department: 'Kingston',
    state: 'Jamaica',
  },
  {
    firstName: 'Shawn',
    lastName: 'Johnson',
    street: '245 Oak Street',
    city: 'Des Moines',
    dateOfBirth: '01/19/1992',
    startDate: '01/01/2007',
    zipCode: '50301',
    department: 'Iowa',
    state: 'USA',
  },
  {
    firstName: 'Eliud',
    lastName: 'Kipchoge',
    street: '250 Maple Avenue',
    city: 'Eldoret',
    dateOfBirth: '11/05/1984',
    startDate: '01/01/2003',
    zipCode: '30100',
    department: 'Uasin Gishu',
    state: 'Kenya',
  },
  {
    firstName: 'Amy',
    lastName: 'Wambach',
    street: '255 Cherry Street',
    city: 'Rochester',
    dateOfBirth: '06/02/1980',
    startDate: '01/01/2001',
    zipCode: '14601',
    department: 'New York',
    state: 'USA',
  },
  {
    firstName: 'Adam',
    lastName: 'Ondra',
    street: '260 Oak Lane',
    city: 'Brno',
    dateOfBirth: '02/05/1993',
    startDate: '01/01/2008',
    zipCode: '60200',
    department: 'South Moravian',
    state: 'Czech Republic',
  },
  {
    firstName: 'Simone',
    lastName: 'Biles',
    street: '265 Maple Road',
    city: 'Spring',
    dateOfBirth: '03/14/1997',
    startDate: '01/01/2013',
    zipCode: '77373',
    department: 'Texas',
    state: 'USA',
  },
  {
    firstName: 'Sachin',
    lastName: 'Tendulkar',
    street: '270 Pine Avenue',
    city: 'Mumbai',
    dateOfBirth: '04/24/1973',
    startDate: '11/15/1989',
    zipCode: '400001',
    department: 'Maharashtra',
    state: 'India',
  },
  {
    firstName: 'Allyson',
    lastName: 'Felix',
    street: '275 Oak Street',
    city: 'Los Angeles',
    dateOfBirth: '11/18/1985',
    startDate: '01/01/2003',
    zipCode: '90001',
    department: 'California',
    state: 'USA',
  },
  {
    firstName: 'Mo',
    lastName: 'Farah',
    street: '280 Maple Avenue',
    city: 'London',
    dateOfBirth: '03/23/1983',
    startDate: '01/01/2001',
    zipCode: 'EC3N 4DR',
    department: 'London',
    state: 'UK',
  },
  {
    firstName: 'Michael',
    lastName: 'Phelps',
    street: '285 Cherry Street',
    city: 'Baltimore',
    dateOfBirth: '06/30/1985',
    startDate: '01/01/2000',
    zipCode: '21201',
    department: 'Maryland',
    state: 'USA',
  },
  {
    firstName: 'Manny',
    lastName: 'Pacquiao',
    street: '290 Oak Lane',
    city: 'General Santos City',
    dateOfBirth: '12/17/1978',
    startDate: '01/01/1995',
    zipCode: '9500',
    department: 'South Cotabato',
    state: 'Philippines',
  },
  {
    firstName: 'Kareem',
    lastName: 'Abdul-Jabbar',
    street: '295 Maple Road',
    city: 'New York',
    dateOfBirth: '04/16/1947',
    startDate: '01/01/1969',
    zipCode: '10001',
    department: 'New York',
    state: 'USA',
  },
  {
    firstName: 'Caroline',
    lastName: 'Marks',
    street: '300 Pine Avenue',
    city: 'Melbourne Beach',
    dateOfBirth: '02/14/2002',
    startDate: '01/01/2018',
    zipCode: '32951',
    department: 'Florida',
    state: 'USA',
  },
  {
    firstName: 'Tom',
    lastName: 'Hanks',
    street: '123 Main Street',
    city: 'Los Angeles',
    dateOfBirth: '07/09/1956',
    startDate: '01/01/1980',
    zipCode: '90001',
    department: 'California',
    state: 'USA',
  },
  {
    firstName: 'Leonardo',
    lastName: 'DiCaprio',
    street: '789 Oak Lane',
    city: 'Los Angeles',
    dateOfBirth: '11/11/1974',
    startDate: '01/01/1989',
    zipCode: '90001',
    department: 'California',
    state: 'USA',
  },
  {
    firstName: 'Julia',
    lastName: 'Roberts',
    street: '123 Maple Avenue',
    city: 'Los Angeles',
    dateOfBirth: '10/28/1967',
    startDate: '01/01/1987',
    zipCode: '90001',
    department: 'California',
    state: 'USA',
  },
  {
    firstName: 'Emma',
    lastName: 'Stone',
    street: '789 Elm Avenue',
    city: 'New York',
    dateOfBirth: '11/06/1988',
    startDate: '01/01/2004',
    zipCode: '10001',
    department: 'New York',
    state: 'USA',
  },
  {
    firstName: 'Denzel',
    lastName: 'Washington',
    street: '123 Main Street',
    city: 'Los Angeles',
    dateOfBirth: '12/28/1954',
    startDate: '01/01/1977',
    zipCode: '90001',
    department: 'California',
    state: 'USA',
  },
  {
    firstName: 'Charlize',
    lastName: 'Theron',
    street: '123 Maple Avenue',
    city: 'Los Angeles',
    dateOfBirth: '08/07/1975',
    startDate: '01/01/1995',
    zipCode: '90001',
    department: 'California',
    state: 'USA',
  },
  {
    firstName: 'Robert',
    lastName: 'Downey Jr.',
    street: '456 Oak Street',
    city: 'Los Angeles',
    dateOfBirth: '04/04/1965',
    startDate: '01/01/1983',
    zipCode: '90001',
    department: 'California',
    state: 'USA',
  },
  {
    firstName: 'George',
    lastName: 'Clooney',
    street: '123 Main Street',
    city: 'Los Angeles',
    dateOfBirth: '05/06/1961',
    startDate: '01/01/1984',
    zipCode: '90001',
    department: 'California',
    state: 'USA',
  },
  {
    firstName: 'Scarlett',
    lastName: 'Johansson',
    street: '123 Maple Avenue',
    city: 'New York',
    dateOfBirth: '11/22/1984',
    startDate: '01/01/1996',
    zipCode: '10001',
    department: 'New York',
    state: 'USA',
  },
  {
    firstName: 'Angelina',
    lastName: 'Jolie',
    street: '789 Elm Avenue',
    city: 'Los Angeles',
    dateOfBirth: '06/04/1975',
    startDate: '01/01/1993',
    zipCode: '90001',
    department: 'California',
    state: 'USA',
  },
  {
    firstName: 'Chris',
    lastName: 'Hemsworth',
    street: '123 Main Street',
    city: 'Los Angeles',
    dateOfBirth: '08/11/1983',
    startDate: '01/01/2004',
    zipCode: '90001',
    department: 'California',
    state: 'USA',
  },
  {
    firstName: 'Matt',
    lastName: 'Damon',
    street: '789 Oak Lane',
    city: 'Los Angeles',
    dateOfBirth: '10/08/1970',
    startDate: '01/01/1988',
    zipCode: '90001',
    department: 'California',
    state: 'USA',
  },
  {
    firstName: 'Harrison',
    lastName: 'Ford',
    street: '123 Maple Avenue',
    city: 'Los Angeles',
    dateOfBirth: '07/13/1942',
    startDate: '01/01/1966',
    zipCode: '90001',
    department: 'California',
    state: 'USA',
  },
  {
    firstName: 'Natalie',
    lastName: 'Dormer',
    street: '456 Oak Street',
    city: 'London',
    dateOfBirth: '02/11/1982',
    startDate: '01/01/2005',
    zipCode: 'SW1A',
    department: 'London',
    state: 'UK',
  },
  {
    firstName: 'Kate',
    lastName: 'Winslet',
    street: '123 Main Street',
    city: 'London',
    dateOfBirth: '10/05/1975',
    startDate: '01/01/1994',
    zipCode: 'WC2N',
    department: 'London',
    state: 'UK',
  },
  {
    firstName: 'Christian',
    lastName: 'Bale',
    street: '456 Elm Avenue',
    city: 'Los Angeles',
    dateOfBirth: '01/30/1974',
    startDate: '01/01/1986',
    zipCode: '90001',
    department: 'California',
    state: 'USA',
  },
  {
    firstName: 'Jennifer',
    lastName: 'Aniston',
    street: '789 Oak Lane',
    city: 'Los Angeles',
    dateOfBirth: '02/11/1969',
    startDate: '01/01/1989',
    zipCode: '90001',
    department: 'California',
    state: 'USA',
  },
  {
    firstName: 'Jake',
    lastName: 'Gyllenhaal',
    street: '123 Maple Avenue',
    city: 'Los Angeles',
    dateOfBirth: '12/19/1980',
    startDate: '01/01/1999',
    zipCode: '90001',
    department: 'California',
    state: 'USA',
  },
  {
    firstName: 'Cate',
    lastName: 'Blanchett',
    street: '456 Oak Street',
    city: 'Sydney',
    dateOfBirth: '05/14/1969',
    startDate: '01/01/1992',
    zipCode: '2000',
    department: 'New South Wales',
    state: 'Australia',
  },
  {
    firstName: 'Chris',
    lastName: 'Evans',
    street: '789 Elm Avenue',
    city: 'Boston',
    dateOfBirth: '06/13/1981',
    startDate: '01/01/2000',
    zipCode: '02108',
    department: 'Massachusetts',
    state: 'USA',
  },
  {
    firstName: 'Mila',
    lastName: 'Kunis',
    street: '123 Main Street',
    city: 'Los Angeles',
    dateOfBirth: '08/14/1983',
    startDate: '01/01/1994',
    zipCode: '90001',
    department: 'California',
    state: 'USA',
  },
  {
    firstName: 'Joaquin',
    lastName: 'Phoenix',
    street: '456 Elm Avenue',
    city: 'Los Angeles',
    dateOfBirth: '10/28/1974',
    startDate: '01/01/1985',
    zipCode: '90001',
    department: 'California',
    state: 'USA',
  },
  {
    firstName: 'Amy',
    lastName: 'Adams',
    street: '789 Oak Lane',
    city: 'Los Angeles',
    dateOfBirth: '08/20/1974',
    startDate: '01/01/1999',
    zipCode: '90001',
    department: 'California',
    state: 'USA',
  },
  {
    firstName: 'Daniel',
    lastName: 'Radcliffe',
    street: '123 Maple Avenue',
    city: 'London',
    dateOfBirth: '07/23/1989',
    startDate: '01/01/2001',
    zipCode: 'WC2N',
    department: 'London',
    state: 'UK',
  },
  {
    firstName: 'Robert',
    lastName: 'Pattinson',
    street: '456 Oak Street',
    city: 'London',
    dateOfBirth: '05/13/1986',
    startDate: '01/01/2004',
    zipCode: 'WC2N',
    department: 'London',
    state: 'UK',
  },
  {
    firstName: 'Dwayne',
    lastName: 'Johnson',
    street: '123 Main Street',
    city: 'Los Angeles',
    dateOfBirth: '05/02/1972',
    startDate: '01/01/2001',
    zipCode: '90001',
    department: 'California',
    state: 'USA',
  },
  {
    firstName: 'Michael',
    lastName: 'Fassbender',
    street: '789 Oak Lane',
    city: 'London',
    dateOfBirth: '04/02/1977',
    startDate: '01/01/2001',
    zipCode: 'WC2N',
    department: 'London',
    state: 'UK',
  },
  {
    firstName: 'Sandra',
    lastName: 'Bullock',
    street: '123 Maple Avenue',
    city: 'Los Angeles',
    dateOfBirth: '07/26/1964',
    startDate: '01/01/1987',
    zipCode: '90001',
    department: 'California',
    state: 'USA',
  },
  {
    firstName: 'Naomi',
    lastName: 'Watts',
    street: '789 Elm Avenue',
    city: 'Sydney',
    dateOfBirth: '09/28/1968',
    startDate: '01/01/1986',
    zipCode: '2000',
    department: 'New South Wales',
    state: 'Australia',
  },
  {
    firstName: 'Eddie',
    lastName: 'Redmayne',
    street: '123 Main Street',
    city: 'London',
    dateOfBirth: '01/06/1982',
    startDate: '01/01/2002',
    zipCode: 'WC2N',
    department: 'London',
    state: 'UK',
  },
  {
    firstName: 'Colin',
    lastName: 'Firth',
    street: '789 Oak Lane',
    city: 'London',
    dateOfBirth: '09/10/1960',
    startDate: '01/01/1983',
    zipCode: 'WC2N',
    department: 'London',
    state: 'UK',
  },
  {
    firstName: 'Tom',
    lastName: 'Cruise',
    street: '123 Maple Avenue',
    city: 'Los Angeles',
    dateOfBirth: '07/03/1962',
    startDate: '01/01/1981',
    zipCode: '90001',
    department: 'California',
    state: 'USA',
  },
  {
    firstName: 'Gal',
    lastName: 'Gadot',
    street: '456 Oak Street',
    city: 'Los Angeles',
    dateOfBirth: '04/30/1985',
    startDate: '01/01/2004',
    zipCode: '90001',
    department: 'California',
    state: 'USA',
  },
  {
    firstName: 'Emma',
    lastName: 'Stone',
    street: '123 Main Street',
    city: 'Los Angeles',
    dateOfBirth: '11/06/1988',
    startDate: '01/01/2005',
    zipCode: '90001',
    department: 'California',
    state: 'USA',
  },
  {
    firstName: 'Michelle',
    lastName: 'Williams',
    street: '789 Oak Lane',
    city: 'New York',
    dateOfBirth: '09/09/1980',
    startDate: '01/01/1993',
    zipCode: '10001',
    department: 'New York',
    state: 'USA',
  },
  {
    firstName: 'Brad',
    lastName: 'Pitt',
    street: '123 Maple Avenue',
    city: 'Los Angeles',
    dateOfBirth: '12/18/1963',
    startDate: '01/01/1987',
    zipCode: '90001',
    department: 'California',
    state: 'USA',
  },
  {
    firstName: 'Rachel',
    lastName: 'McAdams',
    street: '456 Oak Street',
    city: 'Los Angeles',
    dateOfBirth: '11/17/1978',
    startDate: '01/01/2002',
    zipCode: '90001',
    department: 'California',
    state: 'USA',
  },
  {
    firstName: 'Anne',
    lastName: 'Hathaway',
    street: '123 Main Street',
    city: 'Los Angeles',
    dateOfBirth: '11/12/1982',
    startDate: '01/01/2001',
    zipCode: '90001',
    department: 'California',
    state: 'USA',
  },
  {
    firstName: 'Chadwick',
    lastName: 'Boseman',
    street: '456 Elm Avenue',
    city: 'Los Angeles',
    dateOfBirth: '11/29/1976',
    startDate: '01/01/2003',
    zipCode: '90001',
    department: 'California',
    state: 'USA',
  },
  {
    firstName: 'Andrew',
    lastName: 'Garfield',
    street: '123 Maple Avenue',
    city: 'London',
    dateOfBirth: '08/20/1983',
    startDate: '01/01/2004',
    zipCode: 'WC2N',
    department: 'London',
    state: 'UK',
  },
  {
    firstName: 'Natalie',
    lastName: 'Portman',
    street: '456 Oak Street',
    city: 'Los Angeles',
    dateOfBirth: '06/09/1981',
    startDate: '01/01/1994',
    zipCode: '90001',
    department: 'California',
    state: 'USA',
  },
  {
    firstName: 'Ryan',
    lastName: 'Gosling',
    street: '789 Elm Avenue',
    city: 'Los Angeles',
    dateOfBirth: '11/12/1980',
    startDate: '01/01/2001',
    zipCode: '90001',
    department: 'California',
    state: 'USA',
  },
  {
    firstName: 'Judi',
    lastName: 'Dench',
    street: '123 Main Street',
    city: 'London',
    dateOfBirth: '12/09/1934',
    startDate: '01/01/1957',
    zipCode: 'WC2N',
    department: 'London',
    state: 'UK',
  },
  {
    firstName: 'Will',
    lastName: 'Smith',
    street: '456 Elm Avenue',
    city: 'Los Angeles',
    dateOfBirth: '09/25/1968',
    startDate: '01/01/1989',
    zipCode: '90001',
    department: 'California',
    state: 'USA',
  },
  {
    firstName: 'Emily',
    lastName: 'Blunt',
    street: '789 Oak Lane',
    city: 'London',
    dateOfBirth: '02/23/1983',
    startDate: '01/01/2003',
    zipCode: 'WC2N',
    department: 'London',
    state: 'UK',
  },
  {
    firstName: 'Ryan',
    lastName: 'Reynolds',
    street: '123 Maple Avenue',
    city: 'Vancouver',
    dateOfBirth: '10/23/1976',
    startDate: '01/01/1998',
    zipCode: 'V6B',
    department: 'British Columbia',
    state: 'Canada',
  },
  {
    firstName: 'Hugh',
    lastName: 'Jackman',
    street: '789 Elm Avenue',
    city: 'Sydney',
    dateOfBirth: '10/12/1968',
    startDate: '01/01/1995',
    zipCode: '2000',
    department: 'New South Wales',
    state: 'Australia',
  },
  {
    firstName: 'Emma',
    lastName: 'Watson',
    street: '123 Main Street',
    city: 'London',
    dateOfBirth: '04/15/1990',
    startDate: '01/01/2001',
    zipCode: 'WC2N',
    department: 'London',
    state: 'UK',
  },
  {
    firstName: 'Chris',
    lastName: 'Hemsworth',
    street: '456 Elm Avenue',
    city: 'Byron Bay',
    dateOfBirth: '08/11/1983',
    startDate: '01/01/2002',
    zipCode: '2481',
    department: 'New South Wales',
    state: 'Australia',
  },
  {
    firstName: 'Meryl',
    lastName: 'Streep',
    street: '789 Oak Lane',
    city: 'New York',
    dateOfBirth: '06/22/1949',
    startDate: '01/01/1975',
    zipCode: '10001',
    department: 'New York',
    state: 'USA',
  },
  {
    firstName: 'Johnny',
    lastName: 'Depp',
    street: '123 Maple Avenue',
    city: 'Los Angeles',
    dateOfBirth: '06/09/1963',
    startDate: '01/01/1984',
    zipCode: '90001',
    department: 'California',
    state: 'USA',
  },
  {
    firstName: 'Daniel',
    lastName: 'Craig',
    street: '789 Elm Avenue',
    city: 'London',
    dateOfBirth: '03/02/1968',
    startDate: '01/01/1992',
    zipCode: 'WC2N',
    department: 'London',
    state: 'UK',
  },
  {
    firstName: 'Jennifer',
    lastName: 'Lawrence',
    street: '123 Main Street',
    city: 'Los Angeles',
    dateOfBirth: '08/15/1990',
    startDate: '01/01/2008',
    zipCode: '90001',
    department: 'California',
    state: 'USA',
  },
  {
    firstName: 'Penelope',
    lastName: 'Cruz',
    street: '789 Oak Lane',
    city: 'Madrid',
    dateOfBirth: '04/28/1974',
    startDate: '01/01/1989',
    zipCode: '28001',
    department: 'Madrid',
    state: 'Spain',
  },
  {
    firstName: 'Chris',
    lastName: 'Evans',
    street: '123 Maple Avenue',
    city: 'Boston',
    dateOfBirth: '06/13/1981',
    startDate: '01/01/2000',
    zipCode: '02108',
    department: 'Massachusetts',
    state: 'USA',
  },
  {
    firstName: 'Cate',
    lastName: 'Blanchett',
    street: '456 Oak Street',
    city: 'Sydney',
    dateOfBirth: '05/14/1969',
    startDate: '01/01/1992',
    zipCode: '2000',
    department: 'New South Wales',
    state: 'Australia',
  },
  {
    firstName: 'Halle',
    lastName: 'Berry',
    street: '123 Main Street',
    city: 'Los Angeles',
    dateOfBirth: '08/14/1966',
    startDate: '01/01/1991',
    zipCode: '90001',
    department: 'California',
    state: 'USA',
  },
  {
    firstName: 'Emma',
    lastName: 'Thompson',
    street: '456 Oak Street',
    city: 'London',
    dateOfBirth: '04/15/1959',
    startDate: '01/01/1982',
    zipCode: 'WC2N',
    department: 'London',
    state: 'UK',
  },
  {
    firstName: 'Aishwarya',
    lastName: 'Rai',
    street: '123 Main Street',
    city: 'Mumbai',
    dateOfBirth: '11/01/1973',
    startDate: '01/01/1997',
    zipCode: '400001',
    department: 'Maharashtra',
    state: 'India',
  },
  {
    firstName: 'Mark',
    lastName: 'Ruffalo',
    street: '456 Elm Avenue',
    city: 'New York',
    dateOfBirth: '11/22/1967',
    startDate: '01/01/1991',
    zipCode: '10001',
    department: 'New York',
    state: 'USA',
  },
  {
    firstName: 'Keira',
    lastName: 'Knightley',
    street: '789 Oak Lane',
    city: 'London',
    dateOfBirth: '03/26/1985',
    startDate: '01/01/1999',
    zipCode: 'WC2N',
    department: 'London',
    state: 'UK',
  },
  {
    firstName: 'Russell',
    lastName: 'Crowe',
    street: '123 Maple Avenue',
    city: 'Sydney',
    dateOfBirth: '04/07/1964',
    startDate: '01/01/1986',
    zipCode: '2000',
    department: 'New South Wales',
    state: 'Australia',
  },
  {
    firstName: 'Nicole',
    lastName: 'Kidman',
    street: '456 Oak Street',
    city: 'Sydney',
    dateOfBirth: '06/20/1967',
    startDate: '01/01/1983',
    zipCode: '2000',
    department: 'New South Wales',
    state: 'Australia',
  },
  {
    firstName: 'Samuel',
    lastName: 'L. Jackson',
    street: '789 Elm Avenue',
    city: 'Los Angeles',
    dateOfBirth: '12/21/1948',
    startDate: '01/01/1972',
    zipCode: '90001',
    department: 'California',
    state: 'USA',
  },
  {
    firstName: 'Zoe',
    lastName: 'Saldana',
    street: '123 Main Street',
    city: 'Los Angeles',
    dateOfBirth: '06/19/1978',
    startDate: '01/01/2000',
    zipCode: '90001',
    department: 'California',
    state: 'USA',
  },
  {
    firstName: 'Tom',
    lastName: 'Hardy',
    street: '456 Elm Avenue',
    city: 'London',
    dateOfBirth: '09/15/1977',
    startDate: '01/01/2001',
    zipCode: 'WC2N',
    department: 'London',
    state: 'UK',
  },
  {
    firstName: 'Idris',
    lastName: 'Elba',
    street: '789 Elm Avenue',
    city: 'London',
    dateOfBirth: '09/06/1972',
    startDate: '01/01/1995',
    zipCode: 'WC2N',
    department: 'London',
    state: 'UK',
  },
  {
    firstName: 'Reese',
    lastName: 'Witherspoon',
    street: '123 Main Street',
    city: 'Los Angeles',
    dateOfBirth: '03/22/1976',
    startDate: '01/01/1991',
    zipCode: '90001',
    department: 'California',
    state: 'USA',
  },
];

export default employees;
